### ISSUE TITLE
Display error on IOS 13.1.3

### ISSUE THREAD

**Issue by aluent-thanh** [RWAP/jquery-ui-touch-punch#10]
I know and I updated version touch-punch 0.2.3 but when i use ios, slider create many mark on the screen the same as image i sent you. (https://prnt.sc/pq0v1j). I test on android, web are ok but when i use IOS i meet it.

**Comment by RWAP** [comment]
But the code on this branch is v1.0.5 - v0.2.3 is the old one...

No-one else has reported any issues on IOS (I don't own an Apple product) - so you would need to create some sample code - it could be your CSS or similar...

**Comment by RWAP** [comment]
It is not even clear from the screenshot what the problem is you are seeing - can you compare it to Android / web version....

**Comment by aluent-thanh** [comment]
I mean when i drag pull bar by hand on Iphone, it has blue streaks on the screen. You can see here.
https://prnt.sc/pqeye7

**Comment by RWAP** [comment]
Oh right - but that is using the slider demo on http://touchpunch.furf.com/ - that site will be using very old javascript and the original touch punch.

Touch punch does NOT affect anything to do with layout / css - it only takes touch movements on a touch device and translates them into mouse movements (basically).

You would need to create your own example (maybe on codepen) which shows this error and then maybe someone can figure out what is happening...

**Comment by aluent-thanh** [comment]
Thank you, i don't understand why it is like that beacuse we don't impact to layout/css. I just found out when we aren't focusing on the slider, we click away after pull bar, some blue streaks will appear.
https://codepen.io/aluent-thanh/pen/ExxbyjW
Issue i met: https://prnt.sc/pqhku9

**Comment by RWAP** [comment]
You will need to use the latest touchpunch (as per this fork - v1.0.5) - you are still linking in v0.2.3 of touchpunch.

I can't test it here except from within a browser's built in iphone emulation, so it will have to be left for iphone users to look at and comment.

**Comment by RWAP** [comment]
Just a thought but if the slider doesn't work without touchpunch - maybe it is a jquery ui bug on iOS in the slider code or slider css - but not fixed because it won't work on iOS out of the box?

We use sliders on our site and no-one has spotted this issue - but then we don't use the latest versions of jquery and jquery-ui

**Comment by aluent-thanh** [comment]
Exactly, i use sliders on web, android aren't problem. New my project uses on ios so i met issue. Thank for your help! Maybe it is conflict somewhere.

**Comment by hbiblia** [comment]
Hola

Esto es un error de Safari que no utiliza la GPU para el render en html, pasa mucho con los `<div>`.

**Solución: Quita las líneas** 
`<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/> `

**Solución: Otro problema que pasa mucho es que no se logra completar el pintado de elementos al hacer droppable de un draggable.** 
`.ui-draggable{ transform: translateZ(0); } `
