### ISSUE TITLE
Version compatibility with 3.4.x

### ISSUE THREAD

**Issue by ashish-k-shah** [RWAP/jquery-ui-touch-punch#11]
Hi,

Thanks for upgrading to the current one after so many years.

Let me know the current upgrade version compatible with the Jquery 3.4.x?

**Comment by RWAP** [comment]
I am using this branch with jQuery v3.4.1 without any issues

**Comment by ashish-k-shah** [comment]
Thanks for the update. I was using previous lib from so many years.  Now want to upgrade so confirming you.

**Comment by melloware** [comment]
Me too using on 3.4.1 with no issues.
