### ISSUE TITLE
Nested sortable with dynamic items

### ISSUE THREAD

**Issue by CPTimario** [RWAP/jquery-ui-touch-punch#13]
I have a nested sortable in which one can add/remove items. 

The problem is whenever an item is dragged so that the items can be sorted, the item used for adding more items can not be clicked anymore.

I tried debugging and saw the problem lies within these lines of codes under the _touchEnd function:
```
var timeMoving = event.timeStamp - this._startedMove;
if (!this._touchMoved || timeMoving < 500) {
  // Simulate the click event
  simulateMouseEvent(event, 'click');
} else {
  var endPos = getTouchCoords(event);
  if ((Math.abs(endPos.x - this._startPos.x) < 10) && (Math.abs(endPos.y - this._startPos.y) < 10)) {

      // If the touch interaction did not move, it should trigger a click
      if (!this._touchMoved || event.originalEvent.changedTouches[0].touchType === 'stylus') {
          // Simulate the click event
          simulateMouseEvent(event, 'click');
      }
  }
}
``` 
The problem is whenever an item is dragged,
- _startedMove remains the same
- _startPos remains the same
- _touchMoved remains true
thus, it can not enter the condition above to be able to simulate a click event.

These are the changes I made in order to solve the problem:
- Under _touchStart function, I moved these following lines of codes
```
// Interaction time
self._startedMove = event.timeStamp;

// Track movement to determine if interaction was a click
self._startPos = getTouchCoords(event);
```
before this
```
// Ignore the event if another widget is already being handled
if (touchHandled || !self._mouseCapture(event.originalEvent.changedTouches[0])) {
  return;
}
```
so that _startedMove and _startPos always get a new value whenever a touch occurs.

- Under the _touchEnd function, I added this
```
// Unset the flag to determine the touch movement stopped
this._touchMoved = false;
```
before this
```
// Unset the flag to allow other widgets to inherit the touch event
touchHandled = false;
```
in order to determine that the touch movement has stopped.

**Comment by RWAP** [comment]
That seems to make sense - so I have incorporated it into the main code
