### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by arun1998** [RWAP/jquery-ui-touch-punch#14]
Just wanted to say that this version of the touch punch fixed the issues I was having with the earlier 0.2 version where the touch drag and drop was working with only some browser versions. With this version, the touch drag drop is working with all versions of all browsers (chrome, ff, IE and Edge) Thanks a lot.

**Comment by RWAP** [comment]
Thank you for the feedback

**Comment by brendon** [comment]
Yes! Well done @RWAP! :D
