### ISSUE TITLE
Close dialog not working

### ISSUE THREAD

**Issue by Thedonsolo** [RWAP/jquery-ui-touch-punch#19]
I created a dialog with jquery ui and when i want to close it, it does nothing.
Without jquery uit touch punch it works as expected.
Chrome v 84 on Android.

Code:

$( ".add_edit_orderrow" ).dialog({
				autoOpen: true,
		                resizable:false,
		                width: ($(window).width() * 0.80),
		                height:($(window).height() * 0.88),
		                modal:true,
		                position:{
			                my: "center",
			                at: "center",
			                of: window,
			            }
});

**Comment by RWAP** [comment]
I use the jQuery UI dialog plus touch-punch quite extensively on one of my sites.  I seem to recall the main issue here was that the close button needed specific css to bring it to the front and ensure that the touch area was in the correct position.

It could be linked to the specific version of jQuery and jQuery UI, CSS issues, or the interaction with another plugin (especially as you have been unable to download a custom version of jQuery UI for a couple of years).

Looking at my own code for opening the jQuery dialog, we did use the following options:

```
            $('#popupBasket').dialog({
                autoOpen: false,
				closeText: "",
                closeOnEscape: true,
                width: 540,
                modal: true,
                resizable: false,
                draggable: false
)
});

``` 
THis is jQuery UI v1.11.4 and jQuery v3.4.1

The CSS is:

```
.ui-dialog-titlebar .close-button-wrap, 
.ui-corner-all .close-button-wrap, 
.ui-helper-clearfix .ui-draggable-handle .close-button-wrap {
    height: 30px;
    position: absolute;
    top: 0;
    right: 0;
    z-index: 10;
}
```

**Comment by RWAP** [comment]
Presume this is working
