### ISSUE TITLE
How to install package with npm or yarn

### ISSUE THREAD

**Issue by stollr** [RWAP/jquery-ui-touch-punch#23]
In this repository there is no package.json and as far as I see it is not registered in npm. So is there no way to install it with npm or yarn?

**Comment by RWAP** [comment]
No - I have no idea how to create those packages - if you wish to do so, please feel free to contribute to this.

**Comment by stollr** [comment]
Done :-)

**Comment by RWAP** [comment]
Many thanks - just trying to understand the npm side

**Comment by RWAP** [comment]
Many thanks - have now added it to npm.
