### ISSUE TITLE
self._mouseCapture is not a function

### ISSUE THREAD

**Issue by dmzone** [RWAP/jquery-ui-touch-punch#35]
I always get this error on Chrome, even in desktop.
self._mouseCapture is not a function
    at mouseProto._touchStart (jquery.ui.touch-punch.js:116:31)
    at HTMLDivElement.dispatch (jquery-3.7.1.min.js:2:40035)
    at v.handle (jquery-3.7.1.min.js:2:38006)

(jQuery UI - v1.13.2)

**Comment by RWAP** [comment]
I don't see that error here - and certainly nothing is reported on Chrome.  That line has been in the code for some years and no-one else has reported the issue so I guess it might be linked to something else...

Do you have jQuery-UI installed and included the mouse widget if you went for a custom download?  
That provides the mouse control.

**Comment by melloware** [comment]
I have also never seen this issue.

**Comment by dmzone** [comment]
I think it was related to some version issue; now i've got the right combination and this issue is gone.

**Comment by RWAP** [comment]
Great that is a relief!
