### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by blutorange** [RWAP/jquery-ui-touch-punch#40]
The NPM package https://www.npmjs.com/package/@rwap/jquery-ui-touch-punch currently is at version 1.0.11. This repository is at version 1.1.5. It would be great if the current version could be published to NPM.  Since this was already prepared in #24, it should hopefully be as simple as running `npm publish`.

primefaces/primefaces#12717

**Comment by RWAP** [comment]
Thanks for the reminder - this has been published to npm.

**Comment by blutorange** [comment]
Thank you very much, that was quick :)
