### ISSUE TITLE
In slider "appendTo" elements are not draggable on ios

### ISSUE THREAD

**Issue by minenkoden** [RWAP/jquery-ui-touch-punch#9]
```
create: function() {
            $('#max-bonus').appendTo($('#bonus-ammount span').get(1));
            $('#min-bonus').appendTo($('#bonus-ammount span').get(0));
        },
```
Handles of slider are working perfectly, but appended elements are not draggable. Working everywhere except ios touch devices.

**Comment by RWAP** [comment]
Can you provide a bit more of example code - I am not sure what you are trying to achieve.

**Comment by minenkoden** [comment]
Thanks for your quick answer! I'll try to clarify
js:
```
var bonusAmmount = $('#bonus-ammount');
bonusAmmount.slider({
            range: true,
            animate: true,
            min: 0,
            max: 1600,
            from: 0,
            `to: 1600,`
            step: 5,
            values: [ 0, 1600 ],
            classes: {
                "ui-slider": "highlight"
            },
            create: function() {
                $('#max-bonus-ammount').appendTo($('#bonus-ammount span').get(1));
                $('#min-bonus-ammount').appendTo($('#bonus-ammount span').get(0));
            },
            slide: function( event, ui ) {
                if(timeout){
                    clearTimeout(timeout);
                }
                localStorage.setItem('bonus-ammount-range', `${ui.values[0]}, ${ui.values[1]}`);
                var handleIndex = $(ui.handle).data('uiSliderHandleIndex');
                var label = handleIndex == 0 ? '#min-bonus-ammount' : '#max-bonus-ammount';
                $(label).html('€' + ui.value).position({
                    my: 'center top',
                    at: 'center bottom',
                    of: ui.handle,
                    offset: "0, 1"
                });
                timeout = setTimeout(function (){
                    reload();
                }, delayTime);
            }
});
 $('#min-bonus-ammount').html('€' + bonusAmmount.slider('values', 0)).position({
            my: 'center top',
            at: 'center bottom',
            of: $('#bonus-ammount span:eq(0)'),
            offset: "0, 1"
 });
 $('#max-bonus-ammount').html('€' + bonusAmmount.slider('values', 1)).position({
            my: 'center top',
            at: 'center bottom',
            of: $('#bonus-ammount span:eq(2)'),
            offset: "0, 1"
 });
```
html:
```
<div type="range" name="bonus-ammount" id="bonus-ammount"></div>
 <span id="min-bonus-ammount" class="bonus-ammount-style"></span>
 <span id="max-bonus-ammount" class="bonus-ammount-style"></span>
```

Screenshot example for iphone/ipad devices:
[https://prntscr.com/p8tpxg](url)

For other devices, android, windows, macos, ubuntu, its working perfectly (can pull both "circles" or "numbers").

**Comment by RWAP** [comment]
Can you please set up a working example on codepen.io - there are errors in your sample code above which stop this from working even in Firefox

**Comment by minenkoden** [comment]
Sure here [codepen](https://codepen.io/minenkoden/pen/jONQjmp)
Tested in browserstack.com iphone 6s
[Screenshot](https://prntscr.com/p8vene)

**Comment by RWAP** [comment]
The codepen works fine here within Friefox and Chrome iphone tester browser (I do not own a smart phone!) - however, your codepen is linking to https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js

That is the old buggy version of touch-punch which has not been updated for some years

You need to use the updated version which is on this github - 
https://github.com/RWAP/jquery-ui-touch-punch/blob/master/jquery.ui.touch-punch.js

See https://codepen.io/rwap/pen/WNeYBVX

**Comment by minenkoden** [comment]
I've tried updated version, same problem. Today I've just increased size of "O" element, now design little bit different but its working :-) Thanks for your help!
